# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # include test files or not, default is true
  tests: false

linters:
  enable:
    - errcheck
    - goimports
    - gofmt
    - revive
    - prealloc
    - whitespace
    - unconvert
    - goconst
    - staticcheck
    - govet
    - gocritic
    - unparam
    - ineffassign
    - errorlint
    - unused
  presets:
    - bugs
    - unused

linters-settings:
  prealloc:
    simple: false
  staticcheck:
    checks: [ "*" ]
  revive:
    ignore-generated-header: true
    severity: error
    rules:
      - name: bare-return
      - name: bool-literal-in-expr
      - name: call-to-gc
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: var-naming
      - name: dot-imports
      - name: package-comments
      - name: range
      - name: struct-tag
      - name: string-of-int
      - name: redefines-builtin-id
      - name: range-val-in-closure
      - name: range-val-address
      - name: receiver-naming
      - name: time-equal
      - name: time-naming
      - name: unexported-return
      - name: exported
      - name: indent-error-flow
      - name: errorf
      - name: unexported-naming
      - name: unconditional-recursion
      - name: empty-lines
      - name: empty-block
      - name: waitgroup-by-value
      - name: constant-logical-expr
      - name: superfluous-else
      - name: datarace
      - name: defer
      - name: optimize-operands-order
      - name: modifies-parameter
      - name: modifies-value-receiver
      - name: nested-structs
      - name: identical-branches
      - name: early-return
      - name: deep-exit
      - name: cyclomatic
        arguments:
          - 30
      - name: atomic
      - name: function-result-limit
        arguments:
          - 3
      - name: unnecessary-stmt
      - name: unreachable-code
      - name: banned-characters
        arguments: [
          "й", "ц", "у", "к", "е", "н", "г", "ш", "щ", "з", "х", "ф", "ы", "в", "а", "п", "р", "о", "л", "д", "ж", "э",
          "я", "ч", "с", "м", "и", "т", "ь", "б", "ю", "ъ", "ё",
          "Й", "Ц", "У", "К", "Е", "Н", "Г", "Ш", "Щ", "З", "Х", "Ф", "Ы", "В", "А", "П", "Р", "О", "Л", "Д", "Ж", "Э",
          "Я", "Ч", "С", "М", "И", "Т", "Ь", "Б", "Ю", "Ъ", "Ё"
        ]
  goimports:
    local-prefixes: github.com/tarmalonchik/speedtest
  govet:
    enable-all: true
    disable:
      - printf
      - fieldalignment
      - shadow

issues:
  exclude-rules:
    - linters:
        - revive
      source: "^//go:generate "
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec